[platformio]
src_dir = .

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_port = /dev/esp32
monitor_speed = 115200
lib_deps =
    madhephaestus/ESP32Encoder @ ^0.10.2
    adafruit/Adafruit MLX90640 @ ^1.1.1
    adafruit/Adafruit BusIO @ ^1.14.5
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
