services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bbiyong-server
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - /opt/bbiyong/data:/app/data
    restart: unless-stopped

  web:
    build:
      context: ../FE/bbiyong-react
      dockerfile: Dockerfile
    container_name: bbiyong-web
    ports:
      - "127.0.0.1:8082:80"
    restart: unless-stopped
